spring.application.name=spring-gateway-api

server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8888/eureka

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

custom.eureka.user-microservice.path=/user/**

#Route Properties
#Route1
spring.cloud.gateway.routes[0].id=user-microservice
spring.cloud.gateway.routes[0].uri=lb://USER-MICROSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=${custom.eureka.user-microservice.path}

