CREATE TABLE payment_entity
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_user_id BIGINT,
    to_user_id   BIGINT,
    amount       DECIMAL                                 NOT NULL,
    payment_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_paymententity PRIMARY KEY (id)
);

CREATE TABLE user_entity
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    auth_token VARCHAR(255)                            NOT NULL,
    money      BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_userentity PRIMARY KEY (id)
);

ALTER TABLE user_entity
    ADD CONSTRAINT uc_userentity_authtoken UNIQUE (auth_token);

ALTER TABLE user_entity
    ADD CONSTRAINT uc_userentity_username UNIQUE (username);

ALTER TABLE payment_entity
    ADD CONSTRAINT FK_PAYMENTENTITY_ON_FROMUSER FOREIGN KEY (from_user_id) REFERENCES user_entity (id);

ALTER TABLE payment_entity
    ADD CONSTRAINT FK_PAYMENTENTITY_ON_TOUSER FOREIGN KEY (to_user_id) REFERENCES user_entity (id);
